# First line in pipeline CI
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependences
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

      - name: Run tests with pytest-cov
        run: pytest --cov=features --cov=src tests/

      - name: Run Behave
        run: behave

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Falló el build de pruebas en ${{ github.repository }} en la rama ${{ github.ref_name }}.\n🔗 Ver detalles: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

